### ISSUE TITLE
Some problems with the unpacker.

### ISSUE THREAD

**Issue by Alan1701** [cawk/ConfuserEx-Unpacker#1]
1. Local variables (uint32) that are created during cflow-obfuscation are not cleared.
2. Not all switches are being processed.

**Comment by cawk** [comment]
Please show me a screenshot of the uint32 That's not being removed and send me the file it fails to clean control flow and I'll look into fixing it

**Comment by Alan1701** [comment]
1. original http://i.imgur.com/n1SQt0y.jpg
clean http://i.imgur.com/nrxGzCH.jpg
I tried to fix the removal of unnecessary uint32 through "blocks.OptimizeLocals", but probably not enough skill.
2. http://fileshare.link/1d74380472fcc770/temp.rar (TinyWall)
In the archive files:
  Original.exe - unmodified application.
  Cflow_obfuscated.exe - an application that was obfuscated only with cflow
  Cleaned.exe - an application that was not fully recovered. For example, Microsoft.Samples.PrivateCallback contains the obfuscation even after cleaning.
Thx.

**Comment by cawk** [comment]
Regarding the local i left that in, incase control flow failed anywhere as if I removed the local and control flow failed the method would be corrupt as that locals missing 

And I will take a look at the bug with control flow in the next day or so!

It's most likely a bug I've fixed before that I forgot to push the update for as this tool isn't used that much

**Comment by cawk** [comment]
also please upload that file somewhere else as this is just filled with ads

use zippyshare.com

**Comment by Alan1701** [comment]
thanks for the reply

reupload: http://www77.zippyshare.com/v/A8ANanTc/file.html

**Comment by cawk** [comment]
indeed a bug id fixed before
the issue was switch inside the control flow meaning the fallthrough block was incorrect when replacing (who flow broke)

regarding the locals im not going to add a removal for that since i see more damage than good if i add it 

but if you want to add it inside the controlflow class after the cleaning is done add this line
blocks.Method.Body.Variables.Remove(localSwitch);

this will remove the local 

please update me if you still have an issue with control flow but as far as i can see the latest commit fixes that issue

**Comment by Alan1701** [comment]
Your application is really good. I used "ConfuserExSwitchKiller" ( https://pastebin.com/b6sU3Yd3 ) from CodeCracker before, but I noticed that it changes the logic of conditional statements, which greatly complicates the understanding of the code. But your application is much better, I hope you will develop it further.

**Comment by cawk** [comment]
so did this commit fix all methods that were not previously cleaned? 

and i had plans to fully support all methods but i got lazy and never actually finished it maybe one day but i have no intentions of doing it anytime soon

**Comment by Alan1701** [comment]
Hmm, nothing has changed ...

PKSoft.ConnectionsForm.UpdateList
Microsoft.Samples.PrivateCallback

Still contain cflow obfuscation.

**Comment by cawk** [comment]
may you screenshot this as for me this is completely cleaned

please check you have got the latest commit

**Comment by Alan1701** [comment]
Nothing changed. I used the last commit.

Microsoft.Samples.PrivateCallback http://i.imgur.com/t8HwM16.jpg http://i.imgur.com/FZaM4mi.jpg
PKSoft.ConnectionsForm.UpdateList http://i.imgur.com/9IOWBpf.jpg http://i.imgur.com/wxInfEp.jpg

**Comment by Alan1701** [comment]
Oh, I'm sorry. Everything is fine, I did not put that file ... thanks.
