### ISSUE TITLE
Not working in .Net dll (mixed mode)

### ISSUE THREAD

**Issue by dnvthv** [cawk/ConfuserEx-Unpacker#3]
Hi,

I try to unpack .Net dll (Mixed mode), Message below: 
Yeah confuserex unpacker so what
[!] Anti Tamper Detected
[!] Anti Tamper Removed Successfully
[!] Cleaning Proxy Calls
[!] Amount Of Proxy Calls Fixed: 0
[!] Decrytping Strings
error happened somewhere apart from tamper and packer im too lazy to implement proper error handling

How to fix this?

[Test.zip](https://github.com/cawk/ConfuserEx-Unpacker/files/1592830/Test.zip)

**Comment by cawk** [comment]
this does not support mixed mode assemblies

you can try the dynamic mode on windows 7 or below that might work

**Comment by sasha2002** [comment]
Hi, also have this problem. Not mixed mode.
Yeah confuserex unpacker so what
[!] Anti Tamper Detected
[!] Anti Tamper Removed Successfully
[!] Cleaning Proxy Calls
[!] Amount Of Proxy Calls Fixed: 0
[!] Decrytping Strings
error happened somewhere apart from tamper and packer im too lazy to implement proper error handling
@cawk can you took a look?
