### ISSUE TITLE
Fix compiler for new Dnlib 3.0 and de4dot

### ISSUE THREAD

**Issue by Deltafox79** [cawk/ConfuserEx-Unpacker#6]
into ConfuserEx Dynamic Unpacker source :

1) find all occurence of **MetaData** and change whit **Metadata** -> case sensitive

2) find all occurence of **MetaDataFlags** and change whit **MetadataFlags** -> case sensitive

3) find all occurence of **MetaDataOptions** and change whit **MetadataOptions** -> case sensitive

2) in **Packer.cs**

 `var row = module.TablesStream.ReadFileRow(rid);` 

to

`dnlib.DotNet.MD.RawFileRow row = new dnlib.DotNet.MD.RawFileRow();
                module.TablesStream.TryReadFileRow(rid, out row);`

3) in **Program.cs**

`var htdgfd = (module).Metadata.PEImage.CreateFullStream();`

to

`var htdgfd = (module).Metadata.PEImage.CreateReader();`

Regards

**Comment by cawk** [comment]
Do you want to make a PR for it?

**Comment by Deltafox79** [comment]
Done

**Comment by cawk** [comment]
Thanks
